/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/site'
import { Route as ConteudosGratisRouteImport } from './routes/conteudos-gratis'

const SiteRoute = SiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosGratisRoute = ConteudosGratisRouteImport.update({
  id: '/conteudos-gratis',
  path: '/conteudos-gratis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/conteudos-gratis': typeof ConteudosGratisRoute
  '/site': typeof SiteRoute
}
export interface FileRoutesByTo {
  '/conteudos-gratis': typeof ConteudosGratisRoute
  '/site': typeof SiteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/conteudos-gratis': typeof ConteudosGratisRoute
  '/site': typeof SiteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/conteudos-gratis' | '/site'
  fileRoutesByTo: FileRoutesByTo
  to: '/conteudos-gratis' | '/site'
  id: '__root__' | '/conteudos-gratis' | '/site'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ConteudosGratisRoute: typeof ConteudosGratisRoute
  SiteRoute: typeof SiteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/site': {
      id: '/site'
      path: '/site'
      fullPath: '/site'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos-gratis': {
      id: '/conteudos-gratis'
      path: '/conteudos-gratis'
      fullPath: '/conteudos-gratis'
      preLoaderRoute: typeof ConteudosGratisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ConteudosGratisRoute: ConteudosGratisRoute,
  SiteRoute: SiteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
