/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideochamadaRouteImport } from './routes/videochamada'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as GestacaoRouteImport } from './routes/gestacao'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtlasSlugRouteImport } from './routes/atlas.$slug'
import { Route as AuthenticatedMembroRouteImport } from './routes/_authenticated/membro'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicHotmartWebhookRouteImport } from './routes/api/public/hotmart-webhook'
import { Route as AuthenticatedAtlasSlugAprenderRouteImport } from './routes/_authenticated/atlas.$slug.aprender'

const VideochamadaRoute = VideochamadaRouteImport.update({
  id: '/videochamada',
  path: '/videochamada',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const GestacaoRoute = GestacaoRouteImport.update({
  id: '/gestacao',
  path: '/gestacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasSlugRoute = AtlasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AtlasRoute,
} as any)
const AuthenticatedMembroRoute = AuthenticatedMembroRouteImport.update({
  id: '/membro',
  path: '/membro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicHotmartWebhookRoute = ApiPublicHotmartWebhookRouteImport.update({
  id: '/api/public/hotmart-webhook',
  path: '/api/public/hotmart-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAtlasSlugAprenderRoute =
  AuthenticatedAtlasSlugAprenderRouteImport.update({
    id: '/atlas/$slug/aprender',
    path: '/atlas/$slug/aprender',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/atlas': typeof AtlasRouteWithChildren
  '/gestacao': typeof GestacaoRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/videochamada': typeof VideochamadaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/membro': typeof AuthenticatedMembroRoute
  '/atlas/$slug': typeof AtlasSlugRoute
  '/api/public/hotmart-webhook': typeof ApiPublicHotmartWebhookRoute
  '/atlas/$slug/aprender': typeof AuthenticatedAtlasSlugAprenderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/atlas': typeof AtlasRouteWithChildren
  '/gestacao': typeof GestacaoRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/videochamada': typeof VideochamadaRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/membro': typeof AuthenticatedMembroRoute
  '/atlas/$slug': typeof AtlasSlugRoute
  '/api/public/hotmart-webhook': typeof ApiPublicHotmartWebhookRoute
  '/atlas/$slug/aprender': typeof AuthenticatedAtlasSlugAprenderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/alertas': typeof AlertasRoute
  '/atlas': typeof AtlasRouteWithChildren
  '/gestacao': typeof GestacaoRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/videochamada': typeof VideochamadaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/membro': typeof AuthenticatedMembroRoute
  '/atlas/$slug': typeof AtlasSlugRoute
  '/api/public/hotmart-webhook': typeof ApiPublicHotmartWebhookRoute
  '/_authenticated/atlas/$slug/aprender': typeof AuthenticatedAtlasSlugAprenderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/atlas'
    | '/gestacao'
    | '/home'
    | '/login'
    | '/perfil'
    | '/reset-password'
    | '/videochamada'
    | '/admin'
    | '/membro'
    | '/atlas/$slug'
    | '/api/public/hotmart-webhook'
    | '/atlas/$slug/aprender'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/atlas'
    | '/gestacao'
    | '/home'
    | '/login'
    | '/perfil'
    | '/reset-password'
    | '/videochamada'
    | '/admin'
    | '/membro'
    | '/atlas/$slug'
    | '/api/public/hotmart-webhook'
    | '/atlas/$slug/aprender'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/alertas'
    | '/atlas'
    | '/gestacao'
    | '/home'
    | '/login'
    | '/perfil'
    | '/reset-password'
    | '/videochamada'
    | '/_authenticated/admin'
    | '/_authenticated/membro'
    | '/atlas/$slug'
    | '/api/public/hotmart-webhook'
    | '/_authenticated/atlas/$slug/aprender'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AlertasRoute: typeof AlertasRoute
  AtlasRoute: typeof AtlasRouteWithChildren
  GestacaoRoute: typeof GestacaoRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  PerfilRoute: typeof PerfilRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  VideochamadaRoute: typeof VideochamadaRoute
  ApiPublicHotmartWebhookRoute: typeof ApiPublicHotmartWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videochamada': {
      id: '/videochamada'
      path: '/videochamada'
      fullPath: '/videochamada'
      preLoaderRoute: typeof VideochamadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestacao': {
      id: '/gestacao'
      path: '/gestacao'
      fullPath: '/gestacao'
      preLoaderRoute: typeof GestacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas/$slug': {
      id: '/atlas/$slug'
      path: '/$slug'
      fullPath: '/atlas/$slug'
      preLoaderRoute: typeof AtlasSlugRouteImport
      parentRoute: typeof AtlasRoute
    }
    '/_authenticated/membro': {
      id: '/_authenticated/membro'
      path: '/membro'
      fullPath: '/membro'
      preLoaderRoute: typeof AuthenticatedMembroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hotmart-webhook': {
      id: '/api/public/hotmart-webhook'
      path: '/api/public/hotmart-webhook'
      fullPath: '/api/public/hotmart-webhook'
      preLoaderRoute: typeof ApiPublicHotmartWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/atlas/$slug/aprender': {
      id: '/_authenticated/atlas/$slug/aprender'
      path: '/atlas/$slug/aprender'
      fullPath: '/atlas/$slug/aprender'
      preLoaderRoute: typeof AuthenticatedAtlasSlugAprenderRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMembroRoute: typeof AuthenticatedMembroRoute
  AuthenticatedAtlasSlugAprenderRoute: typeof AuthenticatedAtlasSlugAprenderRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMembroRoute: AuthenticatedMembroRoute,
  AuthenticatedAtlasSlugAprenderRoute: AuthenticatedAtlasSlugAprenderRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AtlasRouteChildren {
  AtlasSlugRoute: typeof AtlasSlugRoute
}

const AtlasRouteChildren: AtlasRouteChildren = {
  AtlasSlugRoute: AtlasSlugRoute,
}

const AtlasRouteWithChildren = AtlasRoute._addFileChildren(AtlasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AlertasRoute: AlertasRoute,
  AtlasRoute: AtlasRouteWithChildren,
  GestacaoRoute: GestacaoRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  PerfilRoute: PerfilRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  VideochamadaRoute: VideochamadaRoute,
  ApiPublicHotmartWebhookRoute: ApiPublicHotmartWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
