// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest, setResponseStatus } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'
import { supabase as browserSupabase } from './client'


function failAuth(message: string, status = 401): never {
  setResponseStatus(status)
  throw new Error(message)
}


// Client-side: forward Supabase access token as Authorization header
const forwardSupabaseAuth = createMiddleware({ type: 'function' }).client(
  async ({ next }) => {
    if (typeof window === 'undefined') return next()

    const { data } = await browserSupabase.auth.getSession()
    const token = data.session?.access_token
    return next({
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    })
  }
)

export const requireSupabaseAuth = createMiddleware({ type: 'function' })
  .middleware([forwardSupabaseAuth])
  .server(
  async ({ next }) => {
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      failAuth(
        'Missing Supabase environment variables. Ensure SUPABASE_URL and SUPABASE_PUBLISHABLE_KEY are set.',
        500,
      )
    }
    
    const request = getRequest();

    if (!request?.headers) {
      failAuth('Unauthorized: No request headers available')
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      failAuth('Unauthorized: No authorization header provided')
    }

    if (!authHeader.startsWith('Bearer ')) {
      failAuth('Unauthorized: Only Bearer tokens are supported')
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      failAuth('Unauthorized: No token provided')
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      failAuth('Unauthorized: Invalid token')
    }

    if (!data.claims.sub) {
      failAuth('Unauthorized: No user ID found in token')
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    })
  }
)
